name: pull request auto response
on:
  pull_request:
   types: [opened]
jobs:
  build:
   name: post welcome comment
   runs-on: ubuntu-latest
   steps:
   - run: gh pr comment $PR_URL --body "Welcome to the Repository My Friend"
     env: 
       GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
       PR_URL: ${{ github.event.pull_request.html_url }}
